#!/usr/bin/env python3
"""Assemble <region>/parts/*.js sub-region fragments into <region>/data.js.

- Fragment filename order becomes sub-region order on the page (hence 01-, 02- prefixes)
- Spots inside each sub-region are auto-sorted north to south by latitude, then renumbered n = 1..k
  Sort coordinates match assets/app.js buildMap: shots[0].view || park || at || spot.at
- Output data.js is `var REGIONS = [...]` so the page can load it with a <script> tag

Usage:
    python3 tools/assemble.py --region dc
    python3 tools/assemble.py --all
"""

import argparse
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
REGIONS = ('yellowstone', 'nyc', 'dc')

# Spots with no shot coordinates use their real-world latitude for sorting (no map pin is created)
FALLBACK_LAT: dict[str, float] = {}

NODE_SCRIPT = r'''
const fs = require('fs');
const path = require('path');
const dir = process.argv[1];
const files = fs.readdirSync(dir).filter(f => f.endsWith('.js')).sort();
const out = files.map(f => {
  const mod = require(path.join(dir, f));
  return { __file: f, ...mod };
});
process.stdout.write(JSON.stringify(out));
'''


def pin_lat(spot):
    """Same lookup order as app.js buildMap."""
    shots = spot.get('shots') or []
    if shots:
        s0 = shots[0]
        for k in ('view', 'park', 'at'):
            if s0.get(k):
                return s0[k][0]
    if spot.get('at'):
        return spot['at'][0]
    return None


def load_parts(region: str):
    parts_dir = ROOT / region / 'parts'
    if not parts_dir.is_dir():
        sys.exit(f'not found: {parts_dir}')
    res = subprocess.run(['node', '-e', NODE_SCRIPT, str(parts_dir)],
                         capture_output=True, text=True, encoding='utf-8')
    if res.returncode != 0:
        sys.exit(f'failed to read fragments for {region}:\n{res.stderr}')
    return json.loads(res.stdout)


def build(region: str) -> int:
    parts = load_parts(region)
    if not parts:
        sys.exit(f'no fragment files under {region}/parts')

    # Researchers first drop a skeleton with empty spots as a placeholder, then fill it in.
    # Half-finished files must not go into data.js, or the page would show an empty sub-region.
    skeletons = [p['__file'] for p in parts if not (p.get('spots') or [])]
    parts = [p for p in parts if p.get('spots')]
    if skeletons:
        print(f'\n  Skipping {len(skeletons)} skeleton fragment(s) with no spots yet (research in progress): '
              + ', '.join(skeletons))
    if not parts:
        sys.exit(f'no fragments with spots yet under {region}/parts')

    seen_spot_ids: dict[str, str] = {}
    seen_region_ids: set[str] = set()
    warnings: list[str] = []

    print(f'\n=== {region} ===')
    for part in parts:
        src = part.pop('__file')
        rid = part.get('id')
        if not rid:
            sys.exit(f'{src} is missing id')
        if rid in seen_region_ids:
            sys.exit(f'{src} has a duplicate sub-region id: {rid}')
        seen_region_ids.add(rid)

        spots = part.get('spots') or []
        if not spots:
            warnings.append(f'{src}: spots is empty')

        # Sort north to south by latitude + renumber
        def sort_key(sp):
            lat = pin_lat(sp)
            if lat is None:
                lat = FALLBACK_LAT.get(sp.get('id', ''), -90.0)
            return -lat

        spots.sort(key=sort_key)
        for i, sp in enumerate(spots, 1):
            sp['n'] = i
            sid = sp.get('id')
            if not sid:
                sys.exit(f'{src} has a spot missing id')
            if sid in seen_spot_ids:
                sys.exit(f'duplicate spot id: {sid} ({src} and {seen_spot_ids[sid]})')
            seen_spot_ids[sid] = src
            if pin_lat(sp) is None:
                warnings.append(f'{src}: {sp.get("en", sid)} has no shot coordinates, so no map pin')
            if not sp.get('images'):
                warnings.append(f'{src}: {sp.get("en", sid)} has no images')

        print(f'  {src:34s} {rid:24s} {len(spots):3d} spots')

    total = sum(len(p.get('spots') or []) for p in parts)
    print(f'  {"total":34s} {len(parts):>24d} sub-regions  {total:3d} spots')

    body = json.dumps(parts, ensure_ascii=False, indent=2)
    header = (
        '/* Generated by tools/assemble.py from %s/parts/*.js. Do not edit directly.\n'
        '   To change the content, edit the matching fragment and re-run:\n'
        '   python3 tools/assemble.py --region %s\n'
        '   Spots are sorted north to south by latitude; the n field is assigned\n'
        '   automatically and matches the map pin numbers one to one. */\n'
    ) % (region, region)
    (ROOT / region / 'data.js').write_text(header + 'var REGIONS = ' + body + ';\n',
                                           encoding='utf-8')

    check = subprocess.run(['node', '--check', str(ROOT / region / 'data.js')],
                           capture_output=True, text=True)
    if check.returncode != 0:
        sys.exit('generated data.js has a syntax problem:\n' + check.stderr)
    print(f'  → {region}/data.js  syntax check passed')

    if warnings:
        print(f'  {len(warnings)} note(s):')
        for w in warnings:
            print('    · ' + w)
    return total


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--region', choices=REGIONS)
    ap.add_argument('--all', action='store_true')
    args = ap.parse_args()

    targets = REGIONS if args.all else ([args.region] if args.region else [])
    if not targets:
        ap.error('need --region or --all')

    grand = 0
    for r in targets:
        if (ROOT / r / 'parts').is_dir():
            grand += build(r)
        else:
            print(f'\n=== {r} === no parts directory yet, skipping')
    if len(targets) > 1:
        print(f'\nThree regions combined: {grand} spots')


if __name__ == '__main__':
    main()
