#!/usr/bin/env python3
"""Reorder spots within each sub-region from north to south by latitude, and renumber n.

Map-pin coordinates come from shots[0].view || shots[0].park || shots[0].at || spot.at
(same as app.js buildMap), so sorting on that same coordinate keeps card numbers
aligned with map numbers.
"""
import argparse
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Set by main() from --region. socal's data.js is hand-maintained;
# other regions are generated by tools/assemble.py (that script sorts itself, so this one is not needed).
DATA = None


def spot_latitudes():
    """Use node to get each sub-region's map-pin latitudes, matching app.js lookup logic."""
    js = """
    eval(require('fs').readFileSync(process.argv[1],'utf8'));
    var out = REGIONS.map(function (r) {
      return {
        name: r.name,
        spots: r.spots.map(function (s) {
          var c = (s.shots && s.shots[0] && (s.shots[0].view || s.shots[0].park || s.shots[0].at)) || s.at;
          return { id: s.id, en: s.en, n: s.n, lat: c ? c[0] : null };
        })
      };
    });
    process.stdout.write(JSON.stringify(out));
    """
    res = subprocess.run(['node', '-e', js, str(DATA)], capture_output=True, text=True)
    if res.returncode != 0:
        sys.exit('node parse failed: ' + res.stderr)
    return json.loads(res.stdout)


def split_spots(block):
    """Split the spots array body into one text chunk per spot."""
    marker = re.compile(r'(?=      \{\n        id: )')
    parts = [p for p in marker.split(block) if p.strip()]
    return parts


def main():
    global DATA
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--region', default='socal',
                    help='region directory name, default socal (other regions are sorted by assemble.py)')
    args = ap.parse_args()

    DATA = ROOT / args.region / 'data.js'
    if not DATA.exists():
        sys.exit(f'cannot find {DATA}')

    regions = spot_latitudes()
    src = DATA.read_text(encoding='utf-8')

    # locate each spots: [ ... ] body
    starts = [m.end() for m in re.finditer(r'\n    spots: \[\n', src)]
    if len(starts) != len(regions):
        sys.exit('spots array count does not match sub-region count')

    ends = []
    for st in starts:
        m = re.compile(r'\n    \]').search(src, st)
        if not m:
            sys.exit('could not find end of spots array')
        ends.append(m.start() + 1)  # keep the newline

    report = []
    # replace from the end so earlier offsets stay valid
    for idx in range(len(regions) - 1, -1, -1):
        region = regions[idx]
        body = src[starts[idx]:ends[idx]]
        chunks = split_spots(body)
        if len(chunks) != len(region['spots']):
            sys.exit('sub-region "%s" has %d text chunks vs %d parsed spots' % (region['name'], len(chunks), len(region['spots'])))

        by_id = {}
        for ch in chunks:
            sid = re.search(r"id: '([^']+)'", ch).group(1)
            by_id[sid] = ch

        # spots with no pin coordinates go to the end of the sub-region. That
        # should not happen in normal data — tools/check_all.py reports it as a pin issue.
        ordered = sorted(region['spots'],
                         key=lambda sp: sp['lat'] if sp['lat'] is not None else -90.0,
                         reverse=True)

        new_chunks = []
        lines = []
        for i, sp in enumerate(ordered, start=1):
            ch = by_id[sp['id']]
            ch, cnt = re.subn(r'\n        n: \d+,\n', '\n        n: %d,\n' % i, ch, count=1)
            if cnt != 1:
                sys.exit('failed to replace n field for spot %s' % sp['id'])
            # strip trailing newline/comma from the chunk and rejoin below, so a former last item without a comma is not moved into the middle
            new_chunks.append(ch.rstrip().rstrip(','))
            moved = '' if sp['n'] == i else '   (was n=%d)' % sp['n']
            lat = '%.4f' % sp['lat'] if sp['lat'] is not None else ' no pin'
            lines.append('  %2d  lat=%s  %s%s' % (i, lat, sp['en'], moved))

        new_body = ',\n'.join(new_chunks) + '\n'
        src = src[:starts[idx]] + new_body + src[ends[idx]:]

        report.append('=== ' + region['name'] + ' ===\n' + '\n'.join(lines))

    DATA.write_text(src, encoding='utf-8')
    for r in reversed(report):
        print(r)
        print()


if __name__ == '__main__':
    main()
